#ifndef REBKEYCODES_H
#define REBKEYCODES_H



enum RebKeyCode {
	RK_NI, RK_LMOUSE, RK_RMOUSE, RK_MMOUSE,
	RK_NUM0, RK_NUM1, RK_NUM2, RK_NUM3, RK_NUM4, RK_NUM5, RK_NUM6, RK_NUM7, RK_NUM8, RK_NUM9,
	RK_NUMDIV, RK_NUMMUL, RK_NUMSUB, RK_NUMADD, RK_NUMENTER, RK_NUMDOT,
	RK_INS, RK_DEL, RK_PGUP, RK_PGDN, RK_HOME, RK_END,
	RK_BACKSPACE, RK_ENTER, RK_SPACE, RK_TAB, RK_CAPSLOCK, RK_LSHIFT, RK_RSHIFT, RK_LCTRL, RK_RCTRL, RK_WIN, RK_LALT, RK_RALT,
	RK_0 = 48, RK_1, RK_2, RK_3, RK_4, RK_5, RK_6, RK_7, RK_8, RK_9,
	RK_UP, RK_DOWN, RK_LEFT, RK_RIGHT,
	RK_A = 65, RK_B, RK_C, RK_D, RK_E, RK_F, RK_G, RK_H, RK_I, RK_J, RK_K, RK_L, RK_M, RK_N, RK_O, RK_P, RK_Q, RK_R, RK_S, RK_T, RK_U, RK_V, RK_W, RK_X, RK_Y, RK_Z,
	RK_F1, RK_F2, RK_F3, RK_F4, RK_F5, RK_F6, RK_F7, RK_F8, RK_F9, RK_F10, RK_F11, RK_F12,
};


#endif